# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.1.0
group=com.cursee.longer_following_time
java_version=21

# Common
minecraft_version=1.21.8
mod_name=Longer Following Time
mod_author=Lupin, Jason13
mod_id=longer_following_time
license=Unlicense
credits=Thanks to Jaredlll08, Darkhax, Serilum, and PacifistMC.
description=Allows animals to follow you for longer after switching held items!
minecraft_version_range=[1.21.8, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.8
parchment_version=2025.07.20

# Fabric
fabric_version=0.130.0+1.21.8
fabric_loader_version=0.17.0

# Forge
forge_version=58.1.0
forge_loader_version_range=[58,)

# NeoForge
neoforge_version=21.8.35
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
